# Currently used for local development and testing purposes. Contains MongoDB and PostgreSQL services databases.
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: HomeHub
    ports:
    - "8081:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dev_db_psql
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: secret

  postgres:
    image: 'postgres:latest'
    container_name: Postgres
    environment:
      - 'POSTGRES_DB=dev_db_psql'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dev'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: